<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>                      
  </head>

  <body></body>
  <script>
    // try catch 基本用法
    const a = null;
    // try{
    //     console.log(a.name);
    // }catch(err){
    //     console.log(err,'抛出的异常');
    // }

    // try catch 用法2
    // try {
    //   if (a == "" || a == null) {
    //     // throw `${a}值为空ya`;
    //     // b;
    //     console.log(a.name);
    //   } else {
    //     console.log(a);
    //   }
    // } catch (err) {
    //   console.log("发生异常", err);
    // } finally{
    //     alert('最终都会走finally')
    // }

    // try catch捕捉异常错误 用法3
    // try {
    //   setTimeout(() => {
    //     // console.log(a.name ,'默认捕捉');
    //     throw "自定义捕捉异常信息";
    //   });
    //   if (!a) {
    //     throw "a值不存在";
    //   }
    // } catch (err) {
    //   console.log("自定义捕捉的异常", err);
    // }

    // try catch捕捉异常错误 用法4
    // let fun = function() {
    //   try {
    //     // throw "强制抛出错误";
    //     console.log("throw也有类型与return强制终止任务的功能");
    //   } catch (err) {
    //     console.log(err);z
    //   } finally {
    //     console.log("最终一点要执行的函数");
    //   }
    //   console.log("----------------");
    // };
    // (function() {
    //   return console.log("立即执行函数");
    // })();
  </script>
</html>
